1: hokkaido
2: aomori
3: iwate
4: miyagi
5: akita
6: yamagata
7: fukushima
8: tochigi
9: gunma
10: ibaraki
11: saitama
12: chiba
13: tokyo
14: kanagawa
15: yamanashi
16: nagano
17: niigata
18: toyama
19: ishikawa
20: fukui
21: shizuoka
22: gifu
23: aichi
24: mie
25: shiga
26: kyoto
27: osaka
28: hyogo
29: nara
30: wakayama
31: tottori
32: shimane
33: okayama
34: hiroshima
35: yamaguchi
36: tokushima
37: kagawa
38: ehime
39: kochi
40: fukuoka
41: saga
42: nagasaki
43: kumamoto
44: ooita
45: miyazaki
46: kagoshima
47: okinawa
